

main : RBT.cpp AVL.cpp BST.cpp utilities.cpp main.cpp
	g++ -g RBT.cpp AVL.cpp BST.cpp utilities.cpp main.cpp -o main

bst : BST.cpp utilities.cpp main.cpp
	g++ -g BST.cpp utilities.cpp main.cpp -o main

avl : AVL.cpp utilities.cpp main.cpp
	g++ -g AVL.cpp utilities.cpp main.cpp -o main

rbt : RBT.cpp utilities.cpp main.cpp
	g++ -g RBT.cpp utilities.cpp main.cpp -o main